# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Mon Sep 28 00:41:32 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(225, 695)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(8, 77, 210, 190))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.MAX_raw = QtGui.QLabel(self.groupBox)
        self.MAX_raw.setGeometry(QtCore.QRect(7, 16, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.MAX_raw.setFont(font)
        self.MAX_raw.setObjectName(_fromUtf8("MAX_raw"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(59, 22, 20, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.MAX_calib = QtGui.QDoubleSpinBox(self.groupBox)
        self.MAX_calib.setGeometry(QtCore.QRect(73, 20, 68, 22))
        self.MAX_calib.setMinimum(-100.0)
        self.MAX_calib.setMaximum(100.0)
        self.MAX_calib.setSingleStep(0.1)
        self.MAX_calib.setObjectName(_fromUtf8("MAX_calib"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(145, 22, 20, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.MAX_Temp = QtGui.QLabel(self.groupBox)
        self.MAX_Temp.setGeometry(QtCore.QRect(158, 17, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.MAX_Temp.setFont(font)
        self.MAX_Temp.setObjectName(_fromUtf8("MAX_Temp"))
        self.sp_MAX = QtGui.QDoubleSpinBox(self.groupBox)
        self.sp_MAX.setGeometry(QtCore.QRect(65, 46, 91, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.sp_MAX.setFont(font)
        self.sp_MAX.setMaximum(199.99)
        self.sp_MAX.setProperty("value", 0.0)
        self.sp_MAX.setObjectName(_fromUtf8("sp_MAX"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 49, 56, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.ctrl_MAX = QtGui.QPushButton(self.groupBox)
        self.ctrl_MAX.setGeometry(QtCore.QRect(119, 111, 58, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.ctrl_MAX.setFont(font)
        self.ctrl_MAX.setCheckable(True)
        self.ctrl_MAX.setChecked(False)
        self.ctrl_MAX.setObjectName(_fromUtf8("ctrl_MAX"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 83, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.MAX_dutycycle = QtGui.QSpinBox(self.groupBox)
        self.MAX_dutycycle.setGeometry(QtCore.QRect(107, 83, 65, 22))
        self.MAX_dutycycle.setMaximum(100)
        self.MAX_dutycycle.setObjectName(_fromUtf8("MAX_dutycycle"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(177, 86, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(5, 114, 47, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(8, 142, 47, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(6, 167, 47, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.autotune_MAX = QtGui.QPushButton(self.groupBox)
        self.autotune_MAX.setGeometry(QtCore.QRect(112, 149, 75, 33))
        self.autotune_MAX.setCheckable(True)
        self.autotune_MAX.setObjectName(_fromUtf8("autotune_MAX"))
        self.MAX_kc = QtGui.QDoubleSpinBox(self.groupBox)
        self.MAX_kc.setGeometry(QtCore.QRect(29, 112, 74, 22))
        self.MAX_kc.setMaximum(9999.0)
        self.MAX_kc.setObjectName(_fromUtf8("MAX_kc"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(5, 312, 47, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(6, 365, 47, 12))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(8, 340, 47, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.MAX_ti = QtGui.QDoubleSpinBox(self.groupBox)
        self.MAX_ti.setGeometry(QtCore.QRect(29, 138, 75, 22))
        self.MAX_ti.setMaximum(99999999.0)
        self.MAX_ti.setObjectName(_fromUtf8("MAX_ti"))
        self.MAX_td = QtGui.QDoubleSpinBox(self.groupBox)
        self.MAX_td.setGeometry(QtCore.QRect(30, 164, 74, 22))
        self.MAX_td.setMaximum(99999999.0)
        self.MAX_td.setObjectName(_fromUtf8("MAX_td"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(8, 275, 210, 190))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.ds_raw = QtGui.QLabel(self.groupBox_2)
        self.ds_raw.setGeometry(QtCore.QRect(8, 15, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.ds_raw.setFont(font)
        self.ds_raw.setObjectName(_fromUtf8("ds_raw"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(59, 20, 20, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.ds_calib = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.ds_calib.setGeometry(QtCore.QRect(74, 20, 68, 22))
        self.ds_calib.setMinimum(-100.0)
        self.ds_calib.setMaximum(100.0)
        self.ds_calib.setSingleStep(0.1)
        self.ds_calib.setObjectName(_fromUtf8("ds_calib"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(143, 23, 20, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ds_Temp = QtGui.QLabel(self.groupBox_2)
        self.ds_Temp.setGeometry(QtCore.QRect(157, 16, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.ds_Temp.setFont(font)
        self.ds_Temp.setObjectName(_fromUtf8("ds_Temp"))
        self.sp_ds = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sp_ds.setGeometry(QtCore.QRect(65, 46, 91, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.sp_ds.setFont(font)
        self.sp_ds.setMaximum(199.99)
        self.sp_ds.setProperty("value", 0.0)
        self.sp_ds.setObjectName(_fromUtf8("sp_ds"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(40, 49, 56, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ctrl_ds = QtGui.QPushButton(self.groupBox_2)
        self.ctrl_ds.setGeometry(QtCore.QRect(121, 113, 58, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.ctrl_ds.setFont(font)
        self.ctrl_ds.setCheckable(True)
        self.ctrl_ds.setChecked(False)
        self.ctrl_ds.setObjectName(_fromUtf8("ctrl_ds"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 83, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ds_dutycycle = QtGui.QSpinBox(self.groupBox_2)
        self.ds_dutycycle.setGeometry(QtCore.QRect(107, 83, 63, 22))
        self.ds_dutycycle.setMaximum(100)
        self.ds_dutycycle.setObjectName(_fromUtf8("ds_dutycycle"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(179, 85, 47, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.autotune_ds = QtGui.QPushButton(self.groupBox_2)
        self.autotune_ds.setGeometry(QtCore.QRect(116, 150, 75, 33))
        self.autotune_ds.setCheckable(True)
        self.autotune_ds.setObjectName(_fromUtf8("autotune_ds"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 141, 47, 12))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(7, 113, 47, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(8, 166, 47, 12))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.ds_kc = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.ds_kc.setGeometry(QtCore.QRect(30, 112, 77, 22))
        self.ds_kc.setMaximum(9999.0)
        self.ds_kc.setObjectName(_fromUtf8("ds_kc"))
        self.ds_ti = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.ds_ti.setGeometry(QtCore.QRect(30, 137, 78, 22))
        self.ds_ti.setMaximum(999999999.0)
        self.ds_ti.setObjectName(_fromUtf8("ds_ti"))
        self.ds_td = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.ds_td.setGeometry(QtCore.QRect(31, 161, 77, 22))
        self.ds_td.setMaximum(999999999.0)
        self.ds_td.setObjectName(_fromUtf8("ds_td"))
        self.connectbut = QtGui.QPushButton(self.centralwidget)
        self.connectbut.setGeometry(QtCore.QRect(107, 6, 104, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.connectbut.setFont(font)
        self.connectbut.setObjectName(_fromUtf8("connectbut"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(5, 10, 47, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.console = QtGui.QTextEdit(self.centralwidget)
        self.console.setEnabled(True)
        self.console.setGeometry(QtCore.QRect(5, 471, 212, 178))
        self.console.setReadOnly(True)
        self.console.setObjectName(_fromUtf8("console"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(8, 34, 212, 44))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.load_but = QtGui.QPushButton(self.groupBox_3)
        self.load_but.setGeometry(QtCore.QRect(19, 15, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.load_but.setFont(font)
        self.load_but.setObjectName(_fromUtf8("load_but"))
        self.save_but = QtGui.QPushButton(self.groupBox_3)
        self.save_but.setGeometry(QtCore.QRect(117, 15, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.save_but.setFont(font)
        self.save_but.setObjectName(_fromUtf8("save_but"))
        self.comlisttext = QtGui.QTextEdit(self.centralwidget)
        self.comlisttext.setGeometry(QtCore.QRect(44, 6, 49, 26))
        self.comlisttext.setObjectName(_fromUtf8("comlisttext"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 225, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperature Controller", None))
        self.groupBox.setTitle(_translate("MainWindow", "MAX31855", None))
        self.MAX_raw.setText(_translate("MainWindow", "n/a", None))
        self.label.setText(_translate("MainWindow", "+", None))
        self.label_2.setText(_translate("MainWindow", "=", None))
        self.MAX_Temp.setText(_translate("MainWindow", "n/a", None))
        self.label_3.setText(_translate("MainWindow", "Sp", None))
        self.ctrl_MAX.setText(_translate("MainWindow", "ON", None))
        self.label_4.setText(_translate("MainWindow", "Duty Cycle:", None))
        self.label_5.setText(_translate("MainWindow", "%", None))
        self.label_6.setText(_translate("MainWindow", "Kc:", None))
        self.label_7.setText(_translate("MainWindow", "Ti:", None))
        self.label_8.setText(_translate("MainWindow", "Td:", None))
        self.autotune_MAX.setText(_translate("MainWindow", "AutoTune", None))
        self.label_14.setText(_translate("MainWindow", "Kc:", None))
        self.label_16.setText(_translate("MainWindow", "Td:", None))
        self.label_15.setText(_translate("MainWindow", "Ti:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "DS18B20", None))
        self.ds_raw.setText(_translate("MainWindow", "n/a", None))
        self.label_9.setText(_translate("MainWindow", "+", None))
        self.label_10.setText(_translate("MainWindow", "=", None))
        self.ds_Temp.setText(_translate("MainWindow", "n/a", None))
        self.label_11.setText(_translate("MainWindow", "Sp", None))
        self.ctrl_ds.setText(_translate("MainWindow", "ON", None))
        self.label_12.setText(_translate("MainWindow", "Duty Cycle:", None))
        self.label_13.setText(_translate("MainWindow", "%", None))
        self.autotune_ds.setText(_translate("MainWindow", "AutoTune", None))
        self.label_20.setText(_translate("MainWindow", "Ti:", None))
        self.label_18.setText(_translate("MainWindow", "Kc:", None))
        self.label_19.setText(_translate("MainWindow", "Td:", None))
        self.connectbut.setText(_translate("MainWindow", "Connect", None))
        self.label_17.setText(_translate("MainWindow", "Port:", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Setting", None))
        self.load_but.setText(_translate("MainWindow", "Load", None))
        self.save_but.setText(_translate("MainWindow", "Save", None))
        self.comlisttext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">COM5</p></body></html>", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionAbout.setText(_translate("MainWindow", "about", None))

